"""update_kb_metadata

Revision ID: 6db6638f50fc
Revises: f2019f6a145e
Create Date: 2026-07-22 22:47:02.303652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6db6638f50fc'
down_revision: Union[str, Sequence[str], None] = 'f2019f6a145e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kb_metadata', sa.Column('training_type', sa.String(), server_default='text', nullable=False))
    op.add_column('kb_metadata', sa.Column('mode', sa.String(), server_default='guideline', nullable=False))
    op.add_column('kb_metadata', sa.Column('country', sa.String(), nullable=True))
    op.add_column('kb_metadata', sa.Column('source_name', sa.String(), server_default='Legacy Source', nullable=False))
    op.add_column('kb_metadata', sa.Column('content_url', sa.String(), nullable=True))
    op.alter_column('kb_metadata', 'source_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('kb_metadata', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kb_metadata', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('kb_metadata', 'source_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('kb_metadata', 'content_url')
    op.drop_column('kb_metadata', 'source_name')
    op.drop_column('kb_metadata', 'country')
    op.drop_column('kb_metadata', 'mode')
    op.drop_column('kb_metadata', 'training_type')
    # ### end Alembic commands ###
