"""add_sft_reviewer

Revision ID: 7e1a8b9c2d3f
Revises: 6db6638f50fc
Create Date: 2026-07-23 22:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '7e1a8b9c2d3f'
down_revision: Union[str, Sequence[str], None] = '6db6638f50fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sft_reviewers',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sft_reviewers_email'), 'sft_reviewers', ['email'], unique=True)
    op.create_index(op.f('ix_sft_reviewers_id'), 'sft_reviewers', ['id'], unique=False)

    op.add_column('rlhf_reviews', sa.Column('retrained_data', sa.Text(), nullable=True))
    op.add_column('rlhf_reviews', sa.Column('grading_tags', sa.JSON(), nullable=True))
    op.add_column('rlhf_reviews', sa.Column('sft_reviewer_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('rlhf_reviews', sa.Column('admin_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'rlhf_reviews', 'sft_reviewers', ['sft_reviewer_id'], ['id'])
    op.create_foreign_key(None, 'rlhf_reviews', 'admins', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rlhf_reviews', type_='foreignkey')
    op.drop_constraint(None, 'rlhf_reviews', type_='foreignkey')
    op.drop_column('rlhf_reviews', 'admin_id')
    op.drop_column('rlhf_reviews', 'sft_reviewer_id')
    op.drop_column('rlhf_reviews', 'grading_tags')
    op.drop_column('rlhf_reviews', 'retrained_data')
    
    op.drop_index(op.f('ix_sft_reviewers_id'), table_name='sft_reviewers')
    op.drop_index(op.f('ix_sft_reviewers_email'), table_name='sft_reviewers')
    op.drop_table('sft_reviewers')
    # ### end Alembic commands ###
