"""add label and description

Revision ID: a1b2c3d4e5f6
Revises: 6db6638f50fc
Create Date: 2026-07-23 13:05:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '6db6638f50fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kb_metadata', sa.Column('label', sa.String(), nullable=True))
    op.add_column('kb_metadata', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kb_metadata', 'description')
    op.drop_column('kb_metadata', 'label')
    # ### end Alembic commands ###
