"""Update SavedResponse schema

Revision ID: f2019f6a145e
Revises: bc23873e1909
Create Date: 2026-07-22 17:46:02.767427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2019f6a145e'
down_revision: Union[str, Sequence[str], None] = 'bc23873e1909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_responses', sa.Column('session_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('saved_responses_topic_id_fkey'), 'saved_responses', type_='foreignkey')
    op.create_foreign_key(None, 'saved_responses', 'chat_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_column('saved_responses', 'topic_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_responses', sa.Column('topic_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'saved_responses', type_='foreignkey')
    op.create_foreign_key(op.f('saved_responses_topic_id_fkey'), 'saved_responses', 'topics', ['topic_id'], ['id'])
    op.drop_column('saved_responses', 'session_id')
    # ### end Alembic commands ###
